### PR TITLE
repair search for subreddits

### PR DESCRIPTION
**Pull request by rbertus2000**
little fix for broken subreddit search and code cleanup after performance merge

### CODE REVIEW

**Comment by ojsef39** [comment]
what exactly does that fix? the "lorex" search problem?

**Comment by rbertus2000** [comment]
In the current alpha build search->subreddit is broken.

**Comment by ojsef39** [comment]
> In the current alpha build search->subreddit is broken.

ahh thanks for the info :)

**Comment by Frostplexx** [comment]
@Kinark could you please review this? Not sure if its a good idea to save subredditIcons in user defaults

**Comment by rbertus2000** [comment]
> @Kinark could you please review this? Not sure if its a good idea to save subredditIcons in user defaults

It isn't and causes crashes in search. That's why I deleted this code. It's a relic from a former PR, that's obsolete after the performance branch merge.

**Comment by Frostplexx** [comment]
Whoops, I somehow missed that you deleted the code, sry.

**Pull request merged**
