### PR TITLE
Sync API Keys and Userdefaults using iCloud

### PR DESCRIPTION
**Pull request by Frostplexx**

### CODE REVIEW

**Review by ojseftest — APPROVED** [review]
test

**Comment by ojsef39** [comment]
@Frostplexx so no icloud sync? or was that done with the export?

**Comment by Frostplexx** [comment]
iCloud sync only for API keys. It seems like it will take a while until the Defaults library supports iCloud sync so I figured I add it for the API only for the moment.

**Comment by ojsef39** [comment]
> iCloud sync only for API keys. It seems like it will take a while until the Defaults library supports iCloud sync so I figured I add it for the API only for the moment.

ahhh yeah that makes sense, thanks for clarifying :)

**Pull request closed without merging**
